### ISSUE TITLE
fix font path

### ISSUE THREAD

**Issue by ChaerilM** [aastrong/themify-icons.scss#1]
could you change font path from ../scss/themify-icons/fonts/themify  to ../themify-icons/fonts/themify or just ./fonts/themify

thanks

**Comment by ibanjo** [comment]
Issue confirmed, the suggested change works correctly with Laravel Mix (Webpack).

**Comment by aastrong** [comment]
Pulled in your fix :)

**Comment by ibanjo** [comment]
Great indeed! I would also recommend deleting that DS_STORE file.

**Comment by aastrong** [comment]
Forgot to closes this issue ages ago :)
all your commits were pulled in.
