### ISSUE TITLE
not working with webpack 2 ?

### ISSUE THREAD

**Issue by ghost** [aastrong/themify-icons.scss#3]
I tried to use it with webpack 2, but got an issue with the fonts path... 
did you test it with webpack ?

I tested the othe npm package  themify-icons-sass + resolve-url-loader package
and adding into build/utils.js

  const resolveUrlLoader = {
    loader: 'resolve-url-loader',
    options: {
      sourceMap: options.sourceMap
    }
  }
working fine as  resolve-url-loader is resolving the font path issue...

**Comment by aastrong** [comment]
Hey there, no i have not tested with webpack 2. 
Not sure when I'll have the time to look into this.
If you see the issue & know the fix - you're welcome to submit a PR and I will pull it into the project.

**Comment by aastrong** [comment]
Going to close this unless someone else has the time to look into the issue. 
If so, ill re-open.
