### ISSUE TITLE
Update package in npm

### ISSUE THREAD

**Issue by viniciuspugliese** [aastrong/themify-icons.scss#5]
The package that is available in npm is out of date and has a path error for the font file.

**Comment by aastrong** [comment]
Hey there! 
I honestly didnt know this repo was on NPM - So i'll look into !

Thanks.

**Comment by aastrong** [comment]
@viniciuspugliesi - I'll work on getting this updated. 
Currently, someone else put this on NPM - so its linked to my github repo - but i am not the administrator of that package. 

I'll see if i can gain access 
Thanks !

**Comment by aastrong** [comment]
I'm getting access to the NPM package, so ill let you know when this is done, and updated.
Cheers. 

@viniciuspugliesi

**Comment by briosheje** [comment]
Issue still persists, the font lookup upon `_path.scss` is wrong:

```
@font-face {
	font-family: 'themify';
	src:url(../scss/themify-icons/fonts/themify.eot?-fvbane);
	src:url(../scss/themify-icons/fonts/themify.eot?#iefix-fvbane) format('embedded-opentype'),
		url(../scss/themify-icons/fonts/themify.woff?-fvbane) format('woff'),
		url(../scss/themify-icons/fonts/themify.ttf?-fvbane) format('truetype'),
		url(../scss/themify-icons/fonts/themify.svg?-fvbane#themify) format('svg');
	font-weight: normal;
	font-style: normal;
}
```

Should be:

```
@font-face {
	font-family: 'themify';
	src:url(./fonts/themify.eot?-fvbane);
	src:url(./fonts/themify-icons/fonts/themify.eot?#iefix-fvbane) format('embedded-opentype'),
		url(./fonts/themify-icons/fonts/themify.woff?-fvbane) format('woff'),
		url(./fonts/themify-icons/fonts/themify.ttf?-fvbane) format('truetype'),
		url(./fonts/themify-icons/fonts/themify.svg?-fvbane#themify) format('svg');
	font-weight: normal;
	font-style: normal;
}
```

**Comment by aastrong** [comment]
@briosheje I've pushed this change to a new branch - as I can't test right now. 

My only concern is that this font structure may not be the same for all senarios / projects - which is why it has a variable right now, and not a hard set path. 

Try your fix above here: https://github.com/aastrong/themify-icons.scss/tree/font-path-update

**Comment by aastrong** [comment]
Pulled in, closing ticket.

**Comment by jepperaskdk** [comment]
I just installed with `npm` and I still see this error.

**Comment by aastrong** [comment]
@jepperaskdk I'm going to take a look at NPM and figure out whats going on. 
Should have an answer in a day or so.
